Repository 10up/animation-best-practices, pull requests merged in 2023-03, with the labels that each got.

#15 Feature: Vector line drawing
  src/examples/illustration/line-drawing/css/index.css
  src/examples/illustration/line-drawing/css/index.html
  src/examples/illustration/line-drawing/css/index.js
  src/examples/illustration/line-drawing/gsap/index.css
  src/examples/illustration/line-drawing/gsap/index.html
  src/examples/illustration/line-drawing/gsap/index.js
  src/examples/illustration/line-drawing/waapi/index.css
  src/examples/illustration/line-drawing/waapi/index.html
  src/examples/illustration/line-drawing/waapi/index.js
Labels: type:enhancement

#16 Feature: Illustration Masking
  src/examples/illustration/masking/css/index.css
  src/examples/illustration/masking/css/index.html
  src/examples/illustration/masking/css/index.js
  src/examples/illustration/masking/gsap/index.css
  src/examples/illustration/masking/gsap/index.html
  src/examples/illustration/masking/gsap/index.js
  src/examples/illustration/masking/images/sprite.png
  src/examples/illustration/masking/waapi/index.css
  src/examples/illustration/masking/waapi/index.html
  src/examples/illustration/masking/waapi/index.js
Labels: type:enhancement

#17 Fix inline JS when used split chunks
  package-lock.json
  package.json
  src/examples/illustration/line-drawing/css/index.html
  src/examples/illustration/line-drawing/gsap/index.html
  src/examples/illustration/line-drawing/waapi/index.html
  src/examples/illustration/masking/css/index.html
  src/examples/illustration/masking/gsap/index.html
  src/examples/illustration/masking/waapi/index.html
  src/examples/ui/accordion/css/index.html
  src/examples/ui/accordion/gsap/index.html
  src/examples/ui/menu/full-screen/css/index.html
  src/examples/ui/menu/full-screen/gsap/index.html
  src/examples/ui/menu/full-screen/waapi/index.html
  src/examples/ui/menu/off-screen/css/index.html
  src/examples/ui/menu/off-screen/gsap/index.html
  src/examples/ui/menu/off-screen/waapi/index.html
  src/examples/ui/page-transition/css/about-us.html
  src/examples/ui/page-transition/css/contact-us.html
  src/examples/ui/page-transition/css/index.html
  src/examples/ui/page-transition/css/services.html
  src/examples/ui/page-transition/gsap/about-us.html
  src/examples/ui/page-transition/gsap/contact-us.html
  src/examples/ui/page-transition/gsap/index.html
  src/examples/ui/page-transition/gsap/services.html
  src/examples/ui/parallax/css/index.html
  src/examples/ui/parallax/gsap/index.html
  webpack.config.js
Labels: type:dependency

#19 Fix: Example Page Transitions
  src/examples/ui/page-transition/css/about-us.html
  src/examples/ui/page-transition/css/contact-us.html
  src/examples/ui/page-transition/css/index.html
  src/examples/ui/page-transition/css/services.html
  src/examples/ui/page-transition/gsap/about-us.html
  src/examples/ui/page-transition/gsap/contact-us.html
  src/examples/ui/page-transition/gsap/index.html
  src/examples/ui/page-transition/gsap/services.html
Labels: type:bug

#20 Fix: Update html-bundler-webpack-plugin to 1.6.2
  package-lock.json
  package.json
Labels: type:dependency

#21 Fix: Menu off screen
  src/examples/ui/menu/off-screen/gsap/index.css
  src/examples/ui/menu/off-screen/gsap/index.js
Labels: type:bug

#18 Feature: Typography marquee
  src/examples/typography/marquee/css/index.css
  src/examples/typography/marquee/css/index.html
  src/examples/typography/marquee/css/index.js
  src/examples/typography/marquee/gsap/index.css
  src/examples/typography/marquee/gsap/index.html
  src/examples/typography/marquee/gsap/index.js
  src/examples/typography/marquee/waapi/index.css
  src/examples/typography/marquee/waapi/index.html
  src/examples/typography/marquee/waapi/index.js
Labels: type:enhancement
